### ISSUE TITLE
Doesn't seem to be fully compatible with ESlint 8

### ISSUE THREAD

**Issue by ACertainCoder** [paweldrozd/eslint-plugin-markdownlint#10]
Hi there,
I'm currently getting the following error with MD013:

```
Error: Fixable rules must set the `meta.fixable` property to "code" or "whitespace".
Occurred while linting <project-path>\Something.md:1
Rule: "markdownlint/md013"
    at Object.report (<project-path>\node_modules\eslint\lib\linter\linter.js:1050:35)
    at <project-path>\node_modules\eslint-plugin-markdownlint\lib\ruleChecker.js:117:35
    at Array.forEach (<anonymous>)
    at reportErrors (<project-path>\node_modules\eslint-plugin-markdownlint\lib\ruleChecker.js:117:10)
    at Program (<project-path>\node_modules\eslint-plugin-markdownlint\lib\ruleChecker.js:128:9)
    at ruleErrorHandler (<project-path>\node_modules\eslint\lib\linter\linter.js:1076:28)
    at <project-path>\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (<project-path>\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (<project-path>\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
```

The migration guide states that 'only rules written as an object are allowed to provide fixes and must have a meta.fixable property set to either "code" or "whitespace"'. Source: <https://eslint.org/docs/latest/use/migrate-to-8.0.0#-rules-require-metafixable-to-provide-fixes>

**Comment by paweldrozd** [comment]
This was fixed in a previous release - all rules now have meta.fixable properly set. The plugin also requires ESLint ≥9 (flat config) since v0.8.0, so ESLint 8 is no longer a supported target.
